Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class RazorController : Controller
    {
        public IActionResult Snacks()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pizza Buona";
}

<div class="container">
    <div class="text-center">
        <h1 class="display-4">Pizza Buona</h1>
        <h4>Miglior pizzeria del Mondo</h4>
        <div class="py-5"></div>
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card">
                    <img src="~/img/margherita.webp" class="card-img-top"
                         alt="Hollywood Sign on The Hill" />
                    <div class="card-body">
                        <h5 class="card-title">Margherita</h5>
                        <p class="card-text">
                            La classica e sempre buonissima pizza fatta con ingredienti genuini e tanto love
                        </p>
                        <p class="card-text">
                            Prezzo: 7 €
                        </p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="~/img/broccoli.webp" class="card-img-top"
                         alt="Hollywood Sign on The Hill" />
                    <div class="card-body">
                        <h5 class="card-title">Verde</h5>
                        <p class="card-text">
                            Pizza con sole verdure e mozzarella
                        </p>
                        <p class="card-text">
                            Prezzo: 9 €
                        </p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="~/img/vegan.webp" class="card-img-top"
                         alt="Hollywood Sign on The Hill" />
                    <div class="card-body">
                        <h5 class="card-title">Vegana</h5>
                        <p class="card-text">
                            Al 100% vegetale, con solo ingredienti bio e crudisti
                        </p>
                        <p class="card-text">
                            Prezzo: 11 €
                        </p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="~/img/mortadella.webp" class="card-img-top"
                         alt="Hollywood Sign on The Hill" />
                    <div class="card-body">
                        <h5 class="card-title">Mortadella</h5>
                        <p class="card-text">
                            Non penso ci sia di meglio, poi metti la burrata nel mezzo e sopra il pistacchio e stai al TOP
                        </p>
                        <p class="card-text">
                            Prezzo: 12 €
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Razor/Snacks.cshtml
@{
    Layout = "_LayoutRazor";
}

<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>

<p>
    1. Dichiarare una variabile valorizzandola con il nostro nome.
    Dichiarare un'altra variabile valorizzandola con il nostro cognome.
    Stampare il nostro nome e cognome all'interno di un tag h2.
</p>
@{
    string Nome = "Constantin";
    string Cognome = "Todirascu";
}
<h2> @Nome @Cognome</h2>

<p>
    2. Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
    Stampare dentro uno span il risultato.
</p>

@{
    int SommaNumeri(int nr){
        int sum = 0;
        for (int i = 1; i <= nr; i++){
            sum += i;
        }

        return sum;
    }
}

<span>@SommaNumeri(6)</span>
<p>
    3. Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina
</p>

@{
    string dante = "nel mezzo del cammin di nostra vita";
}
<span>Il carattere 'a' e presente @dante.Count(d => d == 'a') volte</span>


<p>
    4. Creare una List<int>
        di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70
</p>

@{
    List<int> lista = new List<int>();
    while (lista.Count < 20){
        lista.Add(new Random().Next(1, 91));
    }
}

<ul>
    @{
        foreach (int n in lista)
        {
            if (n >= 20 && n <= 70 ){
                        <li>@n</li>
            }
        }
    }
    
</ul>

<p>
     5. Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi
</p>
<span>Oggi è il @DateTime.Now.ToString("yyy-MM-dd HH:mm:ss")</span>


<p>
    6. Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina
    <ul>
        <li>
            a. la data di 7 giorni fa
        </li>
        <li>
            b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
        </li>

        <li>
            c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
        </li>
    </ul>
    
    
</p>

<ul>
    <li>
        7 giorni fa era @DateTime.Now.Date.AddDays(-7).ToString("dd-MM-yyyy");
    </li>
    <li>
        b. oggi è @DateTime.Now.ToString("dddd");
    </li>

    <li>
        c. tra un anno sarà @DateTime.Now.Date.AddYears(1).ToString("dddd")
    </li>
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Razor" asp-action="Snacks">Snacks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutRazor.cshtml
@RenderBody()